movieRate/movieRate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rateApp/', include('rateApp.urls', namespace='rateApp')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

movieRate/rateApp/urls.py
__author__ = 'pangsm'
from django.conf.urls import url

from rateApp import views

from rateApp.views import HomePageView,movieDetailView,RateCommentView

urlpatterns = [
        url(r'^$',HomePageView.as_view(),name='index'),
        url(r'^(?P<movie_id>\d+)/$',movieDetailView.as_view(), name='detail'),
        url(r'^addRate/$',views.addRate, name='addRate'),
        url(r'^login/$',views.userLogin,name='login'),
        url(r'^register/$',views.register,name='register'),
        url(r'^test1/$',views.test1,name='test1'),
        url(r'^search/$',views.search,name='search'),
        url(r'^rateView/$',RateCommentView.as_view(),name='rateView'),
        url(r'^rateUsefull/(?P<rate_id>\d+)/$',views.rateUsefull,name='rateUsefull'),
      ]

movieRate/rateApp/models.py
from __future__ import unicode_literals

from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible  #this is for chinese compatible
# movie information model
class movieInf(models.Model):
    TYPE_CHOICES = (
        ('Action','action movie'), # First value is stored in db, the second is descriptive
        ('Comedy', 'comedy movie'),
        ('History', 'historical movie'),
        ('Cartoon', 'cartoon movie'),
        ('Document','documentary movie'),
        ('Other','other movie'),
    )
    movie_id = models.IntegerField(primary_key=True)
    movie_name = models.CharField(max_length=96)
    movie_des = models.CharField(max_length=400)
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=200)
    writers = models.CharField(max_length=200)
    movie_date =  models.DateField()
    movie_type = models.CharField(max_length=10,choices=TYPE_CHOICES, default='Action')
    language = models.CharField(max_length=10)
    country = models.CharField(max_length=32)
    length = models.IntegerField()
    alias = models.CharField(max_length=96)
    currentRateValue = models.IntegerField(default=0)
    movie_image = models.ImageField(upload_to='photos', null=True, blank=True)

    def __str__(self):
        return (self.movie_name)

@python_2_unicode_compatible
class userInf(models.Model):
    user_id = models.IntegerField(primary_key=True)
    user_name = models.CharField(max_length=32)
    user_passwd = models.CharField(max_length=32)
    user_alias = models.CharField(max_length=32)

    def __str__(self):
        return(self.user_alias)

@python_2_unicode_compatible
class rateData(models.Model):
    rate_id = models.IntegerField(primary_key=True)
    rate_title = models.CharField(max_length=64)
    movie = models.ForeignKey(movieInf,default='')
    user = models.ForeignKey(userInf,default='')
    rate_score = models.IntegerField()
    rate_comment = models.CharField(max_length=400)
    see_or_not = models.BooleanField()
    rate_date = models.DateField()
    rateusefull = models.IntegerField()
    rateuseless = models.IntegerField()

    def __str__(self):
        return (self.rate_title)




movieRate/rateApp/forms.py

from django import forms
from rateApp.models import userInf,rateData

class UserCreateForm(forms.ModelForm):
    user_passwd = forms.CharField(label='Password',widget=forms.PasswordInput)

    class Meta:
        model = userInf
        fields = ('user_id','user_name','user_passwd','user_alias')

class rateInputForm(forms.ModelForm):
    class Meta:
        model=rateData
        fields=["rate_title", "rate_comment", "rate_date", "see_or_not","rate_score"]
        widgets={"rate_comment": forms.Textarea}

class UserRegisterForm(forms.ModelForm):
    user_passwd = forms.CharField(label='Password',widget=forms.PasswordInput)
    class Meta:
        model = userInf
        fields = ('user_name','user_passwd','user_alias')

movieRate/rateApp/views.py
from __future__ import unicode_literals
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from rateApp.models import movieInf,rateData,userInf
from rateApp.forms import rateInputForm,UserRegisterForm
import datetime
from movieRate import settings

from django.utils.encoding import python_2_unicode_compatible
#@python_2_unicode_compatible  #this is for chinese compatible
# Create your views here.


# home page view function
class HomePageView(TemplateView):
    template_name = "rateApp/index.html"
    def get_context_data(self,**kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['movielist'] =  movieInf.objects.all().order_by('movie_name')[:10]
        context['rateList'] = rateData.objects.all().order_by('rate_score')[:10]
        rateList = rateData.objects.all().order_by('rate_score')[:10]
        context['rateList'] = rateList
        return context

#function of view registed user's rate comment
class RateCommentView(TemplateView):
    template_name = "rateApp/rateView.html"
    def get_context_data(self,**kwargs):
        context = super(RateCommentView, self).get_context_data(**kwargs)
        if settings.cur_user_id > 0:
           user = userInf.objects.get(user_id = settings.cur_user_id)
           context['rateList'] = rateData.objects.filter(user=user)
        else:
           context['user_id'] = 0
        context['user_id'] = settings.cur_user_id
        return context

# function for movie detail information view
class movieDetailView(TemplateView):
     template_name = "rateApp/movieDetail.html"
     def get_context_data(self, **kwargs):
         context = super(movieDetailView, self).get_context_data(**kwargs)
         movieID = context['movie_id']
         settings.cur_movie_id = movieID
         context['movielist'] = movieInf.objects.filter(movie_id=movieID)
         return context

# function for add comment of a movie
def addRate(request):
    if settings.cur_user_id==0:
        return HttpResponseRedirect(reverse('rateApp:login'))
    if request.method == 'POST':
       rateList = rateData.objects.all()
       count = rateList.count()
       count += 1
       #create an object of rateData
       movieobj = movieInf.objects.get(movie_id = settings.cur_movie_id)
       userobj = userInf.objects.get(user_id = settings.cur_user_id)
       obj = rateData()
       obj.rate_id = count
       obj.rate_date = datetime.datetime.now()
       obj.rate_comment = request.POST['rateComment']
       obj.rate_title = request.POST['rateTitle']
       obj.rate_score = request.POST['rateScore']
       obj.movie = movieobj
       obj.user = userobj
       try:
          if request.POST['see']:
            obj.see_or_not = True
          else:
            obj.see_or_not = False
       except:
           obj.see_or_not = False
       obj.rateusefull = 0
       obj.rateuseless = 0
      # save the data
       obj.save()
      #set rate score
       rateList = rateData.objects.filter( movie = movieobj)
       v = 0
       if rateList:
         for rateD in rateList:
            v = v+ rateD.rate_score
         v = v/float(str(rateList.count()))
         v = int(v)/10 - 4
         if v < 0 :
             v = 0
       movies = movieInf.objects.filter(movie_id=settings.cur_movie_id)
       for movie in movies:
          movie.currentRateValue = v
          movie.save()  #save the rate score in movieInf

       return HttpResponseRedirect(reverse('rateApp:index'))
    else:
       return render(request, 'rateApp/addRateData.html')
#function for user login
def userLogin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        usr = user_authenticate(username=username, password=password)
        if usr:
            settings.cur_user_name = usr
            settings.cur_user_id = getUserId(username=username)
            return HttpResponseRedirect(reverse('rateApp:index'))
        else:
            return render(request, 'rateApp/login.html')  # return to login pang
#            return HttpResponse('Your account is disabled.')
    else:
        return render(request, 'rateApp/login.html')

#function for registe a user
def register(request):
    if request.method=='POST':
        form = UserRegisterForm(request.POST,request.FILES)
        if form.is_valid():
             form.save()
             return HttpResponseRedirect(reverse('rateApp:index'))
    else:
        form=UserRegisterForm()
    return render(request, 'rateApp/register.html', {'form':form})
# function for search
def search(request):
    if request.method=='POST':
         searchStr = request.POST['search_text']
         objs = movieInf.objects.filter(movie_name__contains=searchStr)
         if objs:
             movie_id = objs[0].movie_id
             return render(request, 'rateApp/movieDetail.html', {'movielist': objs})
         else:
            objs = movieInf.objects.filter(actors__contains=searchStr)
            if objs:
                return render(request, 'rateApp/movieDetail.html', {'movielist': objs})
            else:
                return HttpResponseRedirect(reverse('rateApp:index'))

    else:
         return HttpResponseRedirect(reverse('rateApp:index'))


# function for testing
def test1(request):
     response=HttpResponse()
     response.write("This is test.")
     rateList = rateData.objects.all().order_by('rate_score')[:10]
     usrNamelist= []
     movieNameList = []
     count = rateList.count()
     response.write(count)
     response.write(",")
     for i in range( count ):
         obj1 = movieInf.objects.filter( movie_id = rateList[i].movie_id  )
         for d in obj1:
            movieNameList.append(d.movie_name)
            response.write(d.movie_name)
            response.write(",")
         obj2 = userInf.objects.filter( user_id = rateList[i].user_id )
         for d1 in obj2:
            usrNamelist.append(d1.user_alias)
            response.write(d1.user_alias)
            response.write(",")
     for j in range( count ):
        response.write(usrNamelist)
        response.write(",")
        response.write(movieNameList)
     return response

def rateUsefull(request,rate_id):
    obj = rateData.objects.get(rate_id=rate_id)
    if obj:
        obj.rateusefull += 1
        obj.save()
    return HttpResponseRedirect(reverse('rateApp:index'))


# function for determining if the user is volid
def user_authenticate(username,password):
    obj = userInf.objects.filter(user_name=username)
    for usr in obj:
        if usr.user_passwd == password :
            return usr.user_alias   # return the user alias
        else:
            s=''
            return s
# function for getting the user ID useing username
def getUserId(username):
    obj = userInf.objects.filter(user_name=username)
    if obj:
        for usr in obj:
            return usr.user_id   # return the user alias
    else:
        return 0


movieRate/rateApp/templates/rateApp/addRateData.html
{% extends 'rateApp/base.html' %}
{% load staticfiles %}
{% block myhdg %}

{% endblock %}

{% block body_block %}

<body>
<br>
<center>

   <lable>

       <h3>Add Movie Rating</h3>

   </lable>
    <br>
          <form action="{% url 'rateApp:addRate' %}" method='POST' class="pull-right">
            {% csrf_token %}
             <label>Please input rate title</label>
            <input name='rateTitle' class="input-small" type="text" placeholder="rate title" size="75">
              <br><br>
              <label>Please input rate comment</label>
              <div>
              <textarea name="rateComment" cols=100 rows=10 placeholder="rate comment">
              </textarea>
              </div>
              <label>Have see it</label>
              <input name="see" type="checkbox" value="see" checked >
              <input name="rateScore" class="input-small" type="text" placeholder="rate score" size="20">
              <br >
              <br><br>
            <button class="btn" type="submit">Submit</button>
          </form>

    </center>
</body>

</html>
{% endblock %}

movieRate/rateApp/templates/rateApp/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{%static 'rateApp/style.css'%}"  />
        <title>Movie Rating - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <div class="menu">
        <br>
      <ul >
          <li style="display:inline; margin-left:20px"><a href="/rateApp/">Home</a></li>
          <li style="display:inline ;margin-left:15px"><a href="{% url 'rateApp:rateView'%}">Rating</a></li>
          <li style="float:right;margin-right:50px;display:inline-block"><a href="{% url 'rateApp:register'%}">Registe</a></li>
          <li style="float:right;margin-right:10px;display:inline-block"><a href="{% url 'rateApp:login'%}">Login</a></li>
      </ul>
    </div>
    <hr style="margin-left: 20px;margin-right: 20px" />
    <br>
    <div class="rate-search">
        <center>
          <form action={% url 'rateApp:search'%}method="post" class="pull-right">
            {% csrf_token %}
            Welcom to Movie Rating <input name='search_text' style="width:400px" class="input-small" type="text" maxlength="100" placeholder="movie name/actor name" >
            <button class="btn" type="submit">Search</button>
          </form>
     </center>
    </div>
    <br>
    <hr style="margin-left: 20px;margin-right: 20px" />
    <body>
      <div id="container">
        <div id="body">
            <h1>{% block myhdg %}Hello {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        <div></div>
    <div id="footer">
    <p>@Developed by Pang Fan All rights reserved University of Winsor Canada </p>
    </div>
    </div>
      </div>
    </body>

</html>

movieRate/rateApp/templates/rateApp/index.html
{% extends 'rateApp/base.html' %}
{% load staticfiles %}
{% block myhdg %}

{% endblock %}

{% block body_block %}
<table>
    <tr >
    <td>
       {% if movielist %}
          <h2 style="margin-left: 30px">List of Movies</h2>
             <div id="layout">
             <ul>
              {% for movie  in movielist %}
                    <li style="float:left"><a href="/rateApp/{{ movie.movie_id }}"><img src="{{ movie.movie_image.url }}" alt="photo" width="100" height="150"/> {{ movie.movie_name }}</a>
                    <div id="image_bottom"><ul>
                    {% if movie.currentRateValue == 0 %}
                        <img src="{% url 'static:rate_6.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% elif movie.currentRateValue == 1 %}
                        <img src="{% url 'static:rate_5.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% elif movie.currentRateValue == 2 %}
                        <img src="{% url 'static:rate_4.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% elif movie.currentRateValue == 3 %}
                        <img src="{% url 'static:rate_3.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% elif movie.currentRateValue == 4 %}
                        <img src="{% url 'static:rate_2.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% elif movie.currentRateValue == 5 %}
                        <img src="{% url 'static:rate_1.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% else %}
                        <img src="{% url 'static:rate_6.jpg' %}" alt="Rank" width="50" height="20"/>
                    {% endif %}
                    </ul>
                    </div>
                    </li>
              {% endfor %}
             </ul>
             </div>

       {% else %}
         <strong>There are no available movie!</strong>
       {% endif %}
    </td>
    </tr><tr><td>
       {% if rateList %}
          <h2 style="margin-left: 30px">List of comment </h2>
          <div>
            <ul>
                {% for rate in  rateList %}
                    <hr>
                    <li> <p style="color:#f00;" ><h3>"{{ rate.rate_title }}"</h3></p>{{ rate.user.user_alias }} Rating {{ rate.movie.movie_name }} on {{ rate.rate_date }}
                        Score:{{ rate.rate_score  }}
                        <ul style="float: right">
                            <li style="float:right;margin-right:50px;display:inline-block"><a  href="/rateApp/rateUsefull/{{ rate.rate_id }}">Was this rating useful?</a> </li>
                            <li style="float:right;margin-right:10px;display:inline-block">{{ rate.rateusefull }}</li>
                        </ul>
                        <br>
                       {{ rate.rate_comment }}
                    </li>
                {% endfor %}
            </ul>
          </div>
       {% endif %}
    </td>
    </tr>
    </table>
  {% endblock %}

movieRate/rateApp/templates/rateApp/login.html
{% extends 'rateApp/base.html' %}
{% block myhdg %}
    User Login
{% endblock %}

{% block body_block %}
<body>
<br>
<center>
   <lable>
       <h3>User Login </h3>
   </lable>
          <form action="{% url 'rateApp:login' %}" method='POST',class="pull-right">
            {% csrf_token %}
            <input name='username' class="input-small" type="text" placeholder="User Name" size="40">
              <br><br>
            <input name='password' class="input-small" type="password" placeholder="Password" size="40">
              <br><br>
            <button class="btn" type="submit">Login</button>
          </form>
          <p> <a href="{% url 'rateApp:register'%}"> Register</a></p>
    </center>
</body>
</html>
{% endblock %}

movieRate/rateApp/templates/rateApp/movieDetail.html
{% extends 'rateApp/base.html' %}
{% load staticfiles %}
{% block myhdg %}

{% endblock %}


{% block body_block %}
    <table>

       {% if movielist %}
           <span>
              {% for movie  in movielist %}
                   <tr><td>
                  <h2 style="margin-left: 120px">{{ movie.movie_name }}</h2>
                   {% if movie.currentRateValue == 0 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_6.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% elif movie.currentRateValue == 1 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_5.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% elif movie.currentRateValue == 2 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_4.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% elif movie.currentRateValue == 3 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_3.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% elif movie.currentRateValue == 4 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_2.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% elif movie.currentRateValue == 5 %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_1.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% else %}
                        <img style="margin-left: 100px" src="{% static 'rateApp/rate_6.jpg' %}" alt="Rank" width="120" height="30"/>
                    {% endif %}
                <ol>
                 <div id="layout">
                   <ul>
                    <li style="float:left;width:200px;"><img src="{{ movie.movie_image.url }}" alt="photo" width="200" height="300"/>
                        <div id="image_bottom"><ul>
                           <a href="/rateApp/addRate">I want rating</a>
                         </ul>
                         </div>
                       </li>
                     <li>
                      <div id="image_info">
                         <ul> <li>导演:{{ movie.director }}</li>
                         <li>主演:{{ movie.actors }}</li>
                         <li>编剧:{{ movie.writers }}</li>
                         <li>日期:{{ movie.movie_date }}</li>
                         <li>语言:{{ movie.language }}</li>
                         <li>国家:{{ movie.country }}</li>
                         <li>片长:{{ movie.length }}</li>
                         <li>别名:{{ movie.alias }}</li>
                         </ul>
                       </div>
                    </li>
                   </ul>
                 </div>
                  </td></tr>

                  <tr><td>
                   <hr />
               <h2 style="margin-left: 30px">Movie Introduction</h2>
               <p style="margin-left:50px;margin-right:50px ">
                {{ movie.movie_des }}
               </p>
                      <hr />
               </td></tr>

              {% endfor %}
           </span>
           </ol>


       {% else %}
         <strong>There are no available movie!</strong>
       {% endif %}
   </table>
  {% endblock %}

movieRate/rateApp/templates/rateApp/rateView.html
{% extends 'rateApp/base.html' %}
{% load staticfiles %}
{% block myhdg %}

{% endblock %}


{% block body_block %}
<table>
{% if user_id  %}
    <tr >
    <td>
       {% if rateList %}
          <h2 style="margin-left: 30px">List of comment </h2>
          <div>
            <ul>
                {% for rate in  rateList %}
                    <hr>
                    <li> <p style="color:#f00;" ><h3>"{{ rate.rate_title }}"<h3></h3> </p>{{ rate.user.user_alias }} Rating {{ rate.movie.movie_name }} on {{ rate.rate_date }}
                        Score:{{ rate.rate_score  }}<br>
                       {{ rate.rate_comment }}
                    </li>
                {% endfor %}
            </ul>
          </div>
       {% endif %}
    </td>
    </tr>
   {% else %}
    <p> Plase login first</p>
   {% endif %}
    </table>
  {% endblock %}

movieRate/rateApp/templates/rateApp/register.html
{% extends 'rateApp/base.html' %}
{% block myhdg %}
  Register a user
{% endblock %}

{% block body_block %}
<body>
    <p>Please ,sign up using the following form:</p>
    <form action='{% url 'rateApp:register' %}' method='POST' >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register a user" />
    </form>
</body>
</html>
{% endblock %}